"""
Prompt templates module
"""

from .templates import (
    SYSTEM_PROMPT,
    TESTLIB_HEADER_COMMENT,
    INIT_PROMPT_TEMPLATE,
    REFINE_PROMPT_TEMPLATE,
    INIT_RESPONSE_TEMPLATE,
    REFINE_RESPONSE_TEMPLATE,
    SOLUTION_RESULT_TEMPLATE,
    TEST_CASE_RESULT_TEMPLATE,
    CANONICAL_SOLUTION_TEMPLATE,
    SOLUTION_CODE_TEMPLATE,
)

__all__ = [
    "SYSTEM_PROMPT",
    "TESTLIB_HEADER_COMMENT",
    "INIT_PROMPT_TEMPLATE",
    "REFINE_PROMPT_TEMPLATE",
    "INIT_RESPONSE_TEMPLATE",
    "REFINE_RESPONSE_TEMPLATE",
    "SOLUTION_RESULT_TEMPLATE",
    "TEST_CASE_RESULT_TEMPLATE",
    "CANONICAL_SOLUTION_TEMPLATE",
    "SOLUTION_CODE_TEMPLATE",
]
